=== astyanax/Project-Xenocide/xna/branches/XNA3.0_branch/Xenocide/Content/Schema/research.xsd
<?xml version="1.0"?>
<xsd:schema xmlns="ResearchConfig"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="ResearchConfig"
	elementFormDefault="qualified"
	attributeFormDefault="unqualified">
	<xsd:include schemaLocation="basic.xsd"/>
	<xsd:simpleType name="researchGrantQuantity">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="AllOf"/>
			<xsd:enumeration value="OneOf"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="refheap">
		<xsd:sequence>
		    <xsd:choice  minOccurs="0" maxOccurs="unbounded">
			    <xsd:element ref="topicref" minOccurs="0" maxOccurs="unbounded"/>
			    <xsd:element ref="itemref" minOccurs="0" maxOccurs="unbounded"/>
			    <xsd:element ref="xnetref" minOccurs="0" maxOccurs="unbounded"/>
			    <xsd:element ref="combatantref" minOccurs="0" maxOccurs="unbounded"/> 
			    <xsd:element ref="facilityref" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:choice>
			<xsd:element name="AnyOneOf" type="refheap" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="AllOf" type="refheap" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="AnyOneOf" type="refheap"/>
	<xsd:element name="AllOf" type="refheap"/>
    <xsd:element name="topicref">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:string">
					<xsd:attribute name="name" type="researchID" use="required"/>
					<xsd:attribute name="priority" type="xsd:string" use="optional"/>
		            <xsd:attribute name="bonus" type="xsd:positiveInteger" use="optional"/>
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="itemref">
		<xsd:complexType>
			<xsd:attribute name="name" type="itemID" use="required"/>
            <xsd:attribute name="bonus" type="xsd:positiveInteger" use="optional"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="facilityref">
		<xsd:complexType>
			<xsd:attribute name="name" type="facilityID" use="required"/>
            <xsd:attribute name="bonus" type="xsd:positiveInteger" use="optional"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="combatantref">
	    <xsd:complexType>
		    <xsd:attribute name="name" type="itemID" use="required"/>
		    <xsd:attribute name="rank" type="rankTypeEnum" use="required"/>
	    </xsd:complexType>
	</xsd:element>
	<xsd:element name="rankref">
	    <xsd:complexType>
		    <xsd:attribute name="rank" type="rankTypeEnum" use="required"/>
            <xsd:attribute name="bonus" type="xsd:positiveInteger" use="optional"/>
	    </xsd:complexType>
	</xsd:element>
	<xsd:element name="xnetref">
		<xsd:complexType>
			<xsd:attribute name="name" type="xnetID" use="required"/>
            <xsd:attribute name="bonus" type="xsd:positiveInteger" use="optional"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="topic">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="prerequisite" type="refheap"/>
				<xsd:element name="cost" minOccurs="0" maxOccurs="1">
					<xsd:complexType>
		                <xsd:sequence minOccurs="1" maxOccurs="unbounded">
			                <xsd:element name="item">
            					<xsd:complexType>
                        			<xsd:attribute name="type" type="itemID" use="required"/>
                        			<xsd:attribute name="quantity" type="xsd:positiveInteger" use="required"/>
            					</xsd:complexType>
        					</xsd:element>
			            </xsd:sequence>
                        <xsd:attribute name="money" type="xsd:nonNegativeInteger"/>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="bonus" minOccurs="0" maxOccurs="1">
					<xsd:complexType>
		                <xsd:choice  minOccurs="1" maxOccurs="unbounded">
			                <xsd:element ref="topicref" minOccurs="0" maxOccurs="unbounded"/>
			                <xsd:element ref="itemref" minOccurs="0" maxOccurs="unbounded"/>
			                <xsd:element ref="xnetref" minOccurs="0" maxOccurs="unbounded"/>
			                <xsd:element ref="rankref" minOccurs="0" maxOccurs="unbounded"/> 
			                <xsd:element ref="facilityref" minOccurs="0" maxOccurs="unbounded"/>
			            </xsd:choice>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="grants">
		            <xsd:complexType>
		                <xsd:choice  minOccurs="1" maxOccurs="unbounded">
			                <xsd:element ref="topicref" minOccurs="0" maxOccurs="unbounded"/>
			                <xsd:element ref="itemref" minOccurs="0" maxOccurs="unbounded"/>
			                <xsd:element ref="xnetref" minOccurs="0" maxOccurs="unbounded"/>
			                <xsd:element ref="combatantref" minOccurs="0" maxOccurs="unbounded"/> 
			                <xsd:element ref="facilityref" minOccurs="0" maxOccurs="unbounded"/>
			            </xsd:choice>
			            <xsd:attribute name="quantity" type="researchGrantQuantity" use="required"/>
		            </xsd:complexType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="id" type="researchID" use="required"/>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="persists" type="xsd:boolean" default="false"/>
			<xsd:attribute name="time" type="xsd:nonNegativeInteger"/>
			<xsd:attribute name="facility" type="facilityID" default="FAC_RESEARCH_FACILITY"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="researchtopics">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="topic" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="title" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== astyanax/Project-Xenocide/xna/branches/Unreviewed_Patches_branch/Xenocide/Content/Schema/research.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
Project Xenocide
Proposed Xenocide Technology Tree 

Created By: Cpt. Boxershorts 
Create Date: 23/01/2004 10:55AM

Edited by: centurion
Edit Date: 5.9.2004
Edit Notes: butchered to get a sample

Edited by: Azrael
Edit Date: 03/04/2005 and onwards
Edit Notes: Filled the tree and edited it many, many, many times.

Edited by: Mad
Edit Date: 28.06.2006
Edit notes: AC is now a prequisite for Silabrate research
		
-->
<researchtopics title="X-Com Tech Tree"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="ResearchConfig"
	xsi:schemaLocation="ResearchConfig
		research.xsd">
	
<!--STARTING TECHNOLOGY-->
	<topic id="RES_STARTING_TECHNOLOGY" name="" time="0">
		<prerequisite>
		</prerequisite>		
		<grants quantity="AllOf">
			<itemref name="ITEM_XC-1_GRYPHON" />
			<xnetref name="XNET_XC-1_GRYPHON" />
			<itemref name="ITEM_XC-11_CONDOR" />
			<xnetref name="XNET_XC-11_CONDOR" />
			<itemref name="ITEM_SIDEWINDER_LIGHT_MISSILE_LAUNCHER" />
			<itemref name="ITEM_SIDEWINDER_LIGHT_MISSILE_CLIP" />
			<xnetref name="XNET_SIDEWINDER_LIGHT_MISSILE" />
			<itemref name="ITEM_TITAN_HEAVY_MISSILE_CLIP" />
			<itemref name="ITEM_TITAN_HEAVY_MISSILE_LAUNCHER" />
			<xnetref name="XNET_TITAN_HEAVY_MISSILE" />
			<itemref name="ITEM_CANNON_CLIP" />
			<itemref name="ITEM_CANNON" />
			<xnetref name="XNET_CANNON" />
			<itemref name="ITEM_XCAP_CANNON_CLIP" />
			<itemref name="ITEM_XCAP_CANNON" />
			<xnetref name="XNET_XCAP,_CANNON" />
			<itemref name="ITEM_XCAP_ROCKET" />
			<xnetref name="XNET_XCAP,_ROCKET" />
			<xnetref name="XNET_XCAP_CHASSIS" />
			<itemref name="ITEM_PISTOL_CLIP" />
			<itemref name="ITEM_PISTOL" />
			<xnetref name="XNET_PISTOL" />
			<itemref name="ITEM_ASSAULT_RIFLE_CLIP" />
			<itemref name="ITEM_ASSAULT_RIFLE" />
			<xnetref name="XNET_ASSAULT_RIFLE" />
			<itemref name="ITEM_H_C_HE_CLIP" />
			<itemref name="ITEM_H_C_AP_CLIP" />
			<itemref name="ITEM_H_C_IN_CLIP" />
			<itemref name="ITEM_HEAVY_CANNON" />
			<xnetref name="XNET_HEAVY_CANNON" />
			<itemref name="ITEM_R_C_HE_CLIP" />
			<itemref name="ITEM_R_C_AP_CLIP" />
			<itemref name="ITEM_R_C_IN_CLIP" />
			<itemref name="ITEM_REPEATER_CANNON" />
			<xnetref name="XNET_REPEATER_CANNON" />
			<itemref name="ITEM_R_L_SMALL_ROCKET" />
			<itemref name="ITEM_R_L_LARGE_ROCKET" />
			<itemref name="ITEM_R_L_IC_ROCKET" />
			<itemref name="ITEM_ROCKET_LAUNCHER" />
			<xnetref name="XNET_ROCKET_LAUNCHER" />
			<itemref name="ITEM_GRENADE" />
			<xnetref name="XNET_GRENADE" />
			<itemref name="ITEM_PROXIMITY_GRENADE" />
			<xnetref name="XNET_PROXIMITY_GRENADE" />
			<itemref name="ITEM_SATCHEL_CHARGE" />
			<xnetref name="XNET_SATCHEL_CHARGE" />
			<itemref name="ITEM_STUN_BATON" />
			<xnetref name="XNET_STUN_BATON" />
			<itemref name="ITEM_FLASHPOD" />
			<xnetref name="XNET_FLASHPOD" />
			<itemref name="ITEM_SMOKE_GRENADE" />
			<xnetref name="XNET_SMOKE_GRENADE" />
			<facilityref name="FAC_BASE_ACCESS_FACILITY" />
			<xnetref name="XNET_BASE_ACCESS_FACILITY" />
			<facilityref name="FAC_BARRACKS_FACILITY" />
			<xnetref name="XNET_BARRACKS_FACILITY" />
			<facilityref name="FAC_RESEARCH_FACILITY" />
			<xnetref name="XNET_RESEARCH_FACILITY" />
			<facilityref name="FAC_ENGINEERING_FACILITY" />
			<xnetref name="XNET_ENGINEERING_FACILITY" />
			<facilityref name="FAC_LANDING_PAD" />
			<xnetref name="XNET_LANDING_PAD" />
			<facilityref name="FAC_STORAGE_FACILITY" />
			<xnetref name="XNET_STORAGE_FACILITY" />
			<facilityref name="FAC_XENOMORPH_HOLDING_FACILITY" />
			<xnetref name="XNET_XENOMORPH_HOLDING_FACILITY" />
			<facilityref name="FAC_SHORT_RANGE_NEUDAR" />
			<xnetref name="XNET_SHORT_RANGE_NEUDAR" />
			<facilityref name="FAC_LONG_RANGE_NEUDAR" />
			<xnetref name="XNET_LONG_RANGE_NEUDAR" />
			<facilityref name="FAC_MISSILE_DEFENSE_ARRAY" />
			<xnetref name="XNET_MISSILE_DEFENSE_ARRAY" />
			<itemref name="ITEM_PERSON_ENGINEER" />
			<itemref name="ITEM_PERSON_SCIENTIST" />
			<itemref name="ITEM_PERSON_SOLDIER" />
			<xnetref name="XNET_STANDARD-ISSUE_BATTLEDRESS_UNIFORM" />
		</grants>
	</topic>
									
<!--ALIEN RESEARCH TOPICS-->
<!--Alien Navigator Interrogation-->
	<topic id="RES_NAVIGATOR_INTERROGATION" name="Navigator Interrogation" time="180">
		<prerequisite>
			<AnyOneOf>
			    <itemref name="ITEM_SATYRIAN_NAVIGATOR"/>
			    <itemref name="ITEM_GREY_NAVIGATOR"/>
        		<itemref name="ITEM_VIPER_NAVIGATOR"/>
    			<itemref name="ITEM_MORLOCK_NAVIGATOR"/>
			</AnyOneOf>
		</prerequisite>		
		<grants quantity="OneOf">
				<xnetref name="XNET_ALIEN_ABDUCTIONS"/>
				<xnetref name="XNET_ALIEN_HARVEST"/>
				<xnetref name="XNET_ALIEN_INFILTRATIONS"/>
				<xnetref name="XNET_ALIEN_RESEARCH"/>
				<xnetref name="XNET_ALIEN_RETALIATION"/>
				<xnetref name="XNET_ALIEN_SUPPLY"/>
				<xnetref name="XNET_ALIEN_TERROR"/>
				<xnetref name="XNET_ALIEN_BASE"/>
		</grants>
	</topic>

<!--Alien Engineer Interrogation-->
	<topic id="RES_ENGINEER_INTERROGATION" name="Engineer Interrogation" time="180" persists="true">
		<prerequisite>
			<AnyOneOf>
    			<itemref name="ITEM_SATYRIAN_ENGINEER"/>
    			<itemref name="ITEM_VIPER_ENGINEER"/>
    			<itemref name="ITEM_GREY_ENGINEER"/>
    			<itemref name="ITEM_MORLOCK_ENGINEER"/>
      </AnyOneOf>
		</prerequisite>		
		<grants quantity="OneOf">
			<xnetref name="XNET_PROBE"/>
			<xnetref name="XNET_RECON"/>
			<xnetref name="XNET_ESCORT"/>
			<xnetref name="XNET_REAPER"/>
			<xnetref name="XNET_COLLECTOR"/>
			<xnetref name="XNET_JUGGERNAUT"/>
			<xnetref name="XNET_INTIMIDATOR"/>
			<xnetref name="XNET_ALIEN_FREIGHTER"/>
		</grants>
	</topic>

<!--Alien Medic Interrogation-->
	<topic id="RES_MEDIC_INTERROGATION" name="Medic Interrogation" time="180" persists="true">
		<prerequisite>
			<AnyOneOf>
			    <itemref name="ITEM_SATYRIAN_MEDIC" />
			    <itemref name="ITEM_GREY_MEDIC" />
			</AnyOneOf>
		</prerequisite>		
		<grants quantity="OneOf">
				<xnetref name="XNET_GREY"/>
				<xnetref name="XNET_GREY_AUTOPSY"/>
				<xnetref name="XNET_MORLOCK"/>
				<xnetref name="XNET_MORLOCK_AUTOPSY"/>
				<xnetref name="XNET_CLOAK"/>
				<xnetref name="XNET_CLOAK_AUTOPSY"/>
				<xnetref name="XNET_ARTOPOD"/>
				<xnetref name="XNET_ARTOPOD_AUTOPSY"/>
				<xnetref name="XNET_TERROR-DISC"/>
				<xnetref name="XNET_TERROR-DISC_AUTOPSY"/>
				<xnetref name="XNET_SILABRATE"/>
				<xnetref name="XNET_SILABRATE_AUTOPSY"/>
				<xnetref name="XNET_VENTRICULANT"/>
				<xnetref name="XNET_VENTRICULANT_AUTOPSY"/>
				<xnetref name="XNET_VIPER"/>
				<xnetref name="XNET_VIPER_AUTOPSY"/>
				<xnetref name="XNET_SATYRIAN"/>
				<xnetref name="XNET_SATYRIAN_AUTOPSY"/>
				<xnetref name="XNET_SPAWN"/>
				<xnetref name="XNET_SPAWN_AUTOPSY"/>
				<xnetref name="XNET_RAPTOR"/>
				<xnetref name="XNET_RAPTOR_AUTOPSY"/>
		</grants>
	</topic>

<!--Alien Leader Interrogation-->
	<topic id="RES_LEADER_INTERROGATION" name="Leader Interrogation" time="180">
		<prerequisite>
			<AnyOneOf>
			    <itemref name="ITEM_SATYRIAN_LEADER"/>
			    <itemref name="ITEM_GREY_LEADER"/>
			    <itemref name="ITEM_VIPER_LEADER"/>
			    <itemref name="ITEM_CLOAK_LEADER"/>
			</AnyOneOf>
		</prerequisite>		
		<grants quantity="AllOf">
			<xnetref name="XNET_ALIEN_INFILTRATIONS"/>
		</grants>
	</topic>	

<!--Alien Commander Interrogation-->
	<topic id="RES_COMMANDER_INTERROGATION" name="Commander Interrogation" time="180">
		<prerequisite>
			<AnyOneOf>
			    <itemref name="ITEM_SATYRIAN_COMMANDER"/>
			    <itemref name="ITEM_GREY_COMMANDER"/>
			    <itemref name="ITEM_VIPER_COMMANDER"/>
			    <itemref name="ITEM_CLOAK_COMMANDER"/>
			</AnyOneOf>
		</prerequisite>		
		<grants quantity="AllOf">
			<xnetref name="XNET_ALIEN_BASE"/>
		</grants>
	</topic>	
	
<!--Alien Origins -->
	<topic id="RES_ALIEN_ORIGINS" name="Alien Origins" time="300">
		<prerequisite>
			<AnyOneOf>
				<itemref name="ITEM_GREY_SOLDIER"/>
				<itemref name="ITEM_GREY_NAVIGATOR"/>
				<itemref name="ITEM_GREY_MEDIC"/>
				<itemref name="ITEM_GREY_ENGINEER"/>
				<itemref name="ITEM_GREY_LEADER"/>
				<itemref name="ITEM_GREY_COMMANDER"/>

				<itemref name="ITEM_SATYRIAN_SOLDIER"/>
				<itemref name="ITEM_SATYRIAN_NAVIGATOR"/>
				<itemref name="ITEM_SATYRIAN_MEDIC"/>
				<itemref name="ITEM_SATYRIAN_ENGINEER"/>
				<itemref name="ITEM_SATYRIAN_LEADER"/>
				<itemref name="ITEM_SATYRIAN_COMMANDER"/>

				<itemref name="ITEM_MORLOCK_SOLDIER"/>
				<itemref name="ITEM_MORLOCK_NAVIGATOR"/>
				<itemref name="ITEM_MORLOCK_ENGINEER"/>

				<itemref name="ITEM_VIPER_SOLDIER"/>
				<itemref name="ITEM_VIPER_NAVIGATOR"/>
				<itemref name="ITEM_VIPER_ENGINEER"/>
				<itemref name="ITEM_VIPER_LEADER"/>
				<itemref name="ITEM_VIPER_COMMANDER"/>

				<itemref name="ITEM_CLOAK_SOLDIER"/>
				<itemref name="ITEM_CLOAK_LEADER"/>
				<itemref name="ITEM_CLOAK_COMMANDER"/>

				<itemref name="ITEM_RAPTOR_TERRORIST"/>
				<itemref name="ITEM_SPAWN_TERRORIST"/>
				<itemref name="ITEM_SILABRATE_TERRORIST"/>
				<itemref name="ITEM_VENTRICULANT_TERRORIST"/>
				<itemref name="ITEM_ARTOPOD_TERRORIST"/>
				<itemref name="ITEM_TERROR_DISC_TERRORIST"/>
			</AnyOneOf>
		</prerequisite>		
		<grants quantity="AllOf">
			<xnetref name="XNET_ALIEN_ORIGINS"/>
		</grants>
	</topic>

<!--Paradigm Shift: Offensive Operations -->
	<topic id="RES_PARADIGM_SHIFT_OFFENSIVE_OPERATIONS" name="Offensive Operations" time="500">
		<prerequisite>
			<xnetref name="XNET_ALIEN_ORIGINS"/>
			<topicref name="RES_LEADER_INTERROGATION"/>
		</prerequisite>
		<grants quantity="AllOf">
			<xnetref name="XNET_PARADIGM_SHIFT:_OFFENSIVE_OPERATIONS"/>
		</grants>
	</topic>	


<!--Thanatos: Project Xenocide -->
