=== astyanax/Project-Xenocide/xna/trunk/Xenocide.MonoGame/Content/Schema/combatant.xsd
<?xml version="1.0"?>
<xsd:schema xmlns="CombatantConfig"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema"
		targetNamespace="CombatantConfig"
		elementFormDefault="qualified"
		attributeFormDefault="unqualified">
	<xsd:include schemaLocation="basic.xsd"/>

	<xsd:complexType name="timeType">
		<xsd:attribute name="days" type="xsd:nonNegativeInteger" default="0"/>
		<xsd:attribute name="hours" type="xsd:nonNegativeInteger" default="0"/>
	</xsd:complexType>
	<xsd:simpleType name="all_const">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="all"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="packet">
		<xsd:simpleContent>
			<xsd:extension base="xsd:positiveInteger">
				<xsd:attribute name="type" use="required">
					<xsd:simpleType>
						<xsd:union memberTypes="money_const itemID"/>
					</xsd:simpleType>
				</xsd:attribute>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	<xsd:complexType name="distribution" abstract="true">
	</xsd:complexType>
	<xsd:complexType name="uniform">
		<xsd:complexContent>
		<xsd:extension base="distribution">
			<xsd:attribute name="min" type="xsd:positiveInteger"/>
			<xsd:attribute name="max" type="xsd:positiveInteger"/>
		</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="normal">
		<xsd:complexContent>
		<xsd:extension base="distribution">
			<xsd:attribute name="mean" type="xsd:positiveInteger"/>
			<xsd:attribute name="variance" type="xsd:nonNegativeInteger"/>
		</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="core">
		<xsd:complexContent>
		<xsd:extension base="distribution">
			<xsd:attribute name="base" type="xsd:nonNegativeInteger" use="required"/>
		</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
  <xsd:complexType name="susceptibility">
    <!-- 
      This specifies how many points of physical and stun damage are applied to 
      combatant, for each point of this type of damage the weapon does to the combatant.
    -->
    <xsd:attribute name="damageType" type="damageTypeEnum" use="required"/>
    <xsd:attribute name="physical"   type="xsd:float"      use="required"/>
    <xsd:attribute name="stun"       type="xsd:float"      use="required"/>
  </xsd:complexType>

	<!-- names of the different loadouts -->
	<xsd:simpleType name="loadoutEnum">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Sampling"/>
			<xsd:enumeration value="LightPlasma"/>
			<xsd:enumeration value="MediumPlasma"/>
			<xsd:enumeration value="HeavyPlasma"/>
			<xsd:enumeration value="Grav"/>
			<xsd:enumeration value="XCorpDefault"/>
			
			<xsd:enumeration value="Ventriculant"/>
			<xsd:enumeration value="Silabrate"/>
			<xsd:enumeration value="Spawn"/>
			<xsd:enumeration value="Artopod"/>
			<xsd:enumeration value="Terrordisc"/>
			<xsd:enumeration value="Raptor"/>
			<xsd:enumeration value="Zombie"/>
		</xsd:restriction>
	</xsd:simpleType>

  <!-- Loadouts (set of items combatant can be equiped with) -->
  <xsd:element name="loadout">
    <xsd:complexType>
    <xsd:sequence>
      <!-- 
        This specifies an item, and where its located
        Co-cordinates are given by InventoryLayout.cs
      -->
      <xsd:element name="item" minOccurs="1" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:attribute name="name" type="itemID"                 use="required"/>
          <xsd:attribute name="x"    type="xsd:nonNegativeInteger" use="required"/>
          <xsd:attribute name="y"    type="xsd:nonNegativeInteger" use="required"/>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
      <xsd:attribute name="name" type="loadoutEnum" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <!-- Armor type -->
  <xsd:element name="armor">
    <xsd:complexType>
    <xsd:sequence>
		<!-- 
		This specifies how many points of physical and stun damage are applied to 
		combatant, for each point of damage of type done to the combatant.
		-->
		<xsd:element name="susceptibility" type="susceptibility" minOccurs="9" maxOccurs="9" />
    </xsd:sequence>
    <xsd:attribute name="id"    type="armorTypeEnum"          use="required"/>
    <xsd:attribute name="front" type="xsd:nonNegativeInteger" use="required"/>
    <xsd:attribute name="side"  type="xsd:nonNegativeInteger" use="required"/>
    <xsd:attribute name="rear"  type="xsd:nonNegativeInteger" use="required"/>
    <xsd:attribute name="under" type="xsd:nonNegativeInteger" use="required"/>
    <!-- does this armor give the wearer the ability to fly? -->
    <xsd:attribute name="flyer" type="xsd:boolean"            use="optional" default="0"/>
    </xsd:complexType>
</xsd:element>

	<!-- where the combatant can carry items -->
	<xsd:simpleType name="carrierEnum">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Humanoid"/>   <!-- Typical soldier inventory configuration -->
			<xsd:enumeration value="Fixed"/>      <!-- Items are fixed, and cant' be viewed or changed. e.g. X-Cap, terrorist -->
		</xsd:restriction>
	</xsd:simpleType>

  <!-- Equipment type -->
  <!-- 
      List of possible loadouts combatant could have, and the odds of
      having each loadout
  -->
  <xsd:element name="equipment">
    <xsd:complexType>
      <xsd:attribute name="loadout" type="loadoutEnum"            use="required"/>
      <xsd:attribute name="odds"    type="xsd:nonNegativeInteger" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <!-- Graphics type -->
  <xsd:element name="graphics">
    <xsd:complexType>
      <xsd:annotation>
        <xsd:documentation>The image/model to put in the view window.
          x, y and z are the rotations in degress about the x, y and z axis to do to the
          model to put it into it's desired orientation when showing in Battlescape
        </xsd:documentation>
      </xsd:annotation>
      <xsd:attribute name="model" type="xsd:string" use="required" />
      <xsd:attribute name="x"     type="xsd:float"  use="required" />
      <xsd:attribute name="y"     type="xsd:float"  use="required" />
      <xsd:attribute name="z"     type="xsd:float"  use="required" />
      <xsd:attribute name="scale" type="xsd:float"  use="optional" default="0.0"/>
    </xsd:complexType>
  </xsd:element>
	
  <!-- Combatant type -->
  <xsd:element name="combatant">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="itemref" minOccurs="0" maxOccurs="1">
				    <!-- Item type to convert this combatant to at end of battlescape -->
					<xsd:complexType>
						<xsd:attribute name="dead"    type="itemID" use="required"/>
						<xsd:attribute name="stunned" type="itemID" use="required"/>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="environments">
					<xsd:complexType>
						<xsd:attribute name="type" use="required">
							<xsd:simpleType>
								<xsd:list itemType="environmentType"/>
							</xsd:simpleType>
						</xsd:attribute>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="attributes">
					<xsd:complexType>
						<xsd:all>
							<xsd:element name="timeunits" type="distribution"/>
							<xsd:element name="stamina" type="distribution"/>
							<xsd:element name="health" type="distribution"/>
							<xsd:element name="bravery" type="distribution" minOccurs="0"/>
							<xsd:element name="reactions" type="distribution"/>
							<xsd:element name="firingaccuracy" type="distribution"/>
							<xsd:element name="throwingaccuracy" type="distribution" minOccurs="0"/>
							<xsd:element name="strength" type="distribution" minOccurs="0"/>
							<xsd:element name="psistrength" type="distribution" minOccurs="0"/>
							<xsd:element name="psiskill" type="distribution" minOccurs="0"/>
							<xsd:element name="energyrecharge" type="distribution" minOccurs="0"/>
							<xsd:element name="victorypoints" type="distribution" minOccurs="0"/>
							<xsd:element name="aggression" type="distribution" minOccurs="0"/>
							<xsd:element name="melee" type="distribution" minOccurs="0"/>
							<xsd:element name="intelligence" type="distribution" minOccurs="0"/>
							<xsd:element name="standingheight" type="distribution" minOccurs="0"/>
							<xsd:element name="kneelingheight" type="distribution" minOccurs="0"/>
							<xsd:element name="floatingheight" type="distribution" minOccurs="0"/>
							<xsd:element name="motionscannerblipsize" type="distribution" minOccurs="0"/>
						</xsd:all>
						<xsd:attribute name="flyer"   type="xsd:boolean" use="optional" default="false"/>
						<xsd:attribute name="carrier" type="carrierEnum" use="optional" default="Humanoid"/>
					</xsd:complexType>
				</xsd:element>
				<xsd:element ref="graphics"  minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="equipment" minOccurs="0"  maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="race"      type="raceTypeEnum"  use="required"/>
			<xsd:attribute name="rank"      type="rankTypeEnum"  use="required"/>
			<xsd:attribute name="armor"     type="armorTypeEnum" use="required"/>

            <!-- If terrorist, the race that uses this terror unit -->
			<xsd:attribute name="ownerRace" type="raceTypeEnum" use="optional"/>
    </xsd:complexType>
	</xsd:element>
	<xsd:element name="combatantdata">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="loadout"   maxOccurs="unbounded"/>
				<xsd:element ref="armor"     maxOccurs="unbounded"/>
				<xsd:element ref="combatant" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== astyanax/Project-Xenocide/xna/trunk/Xenocide/Content/Schema/combatant.xml
<?xml version="1.0" encoding="utf-8" ?> 
<combatantdata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="CombatantConfig" xsi:schemaLocation="CombatantConfig combatant.xsd">

  <!--
    The sets of equipment that a combatant could be wearing
    x and y are position of item, as given by InventoryLayout.cs
        Inventory properties are stored in a grid like
        +=+=+===+=====+
        |g|h|f f|b b b|
        +=+=+===+     |
        |a a a a|b b b|
        + +===+ +     |
        |a|c c|a|b b b|
        +=+=+=+=+=+===+
        |d d|e e|i|   |
        +===+===+=+===+
        where
            a = belt
            b = backpack
            c = right shoulder
            d = right leg
            e = left shoulder
            f = left leg
            g = right hand
            h = left hand
            i = armor
-->
  <loadout name="Sampling">
    <item name="ITEM_STUN_LAUNCHER" x="0" y="0" />
    <item name="ITEM_PSIONIC_PROBE" x="1" y="0" />
    <item name="ITEM_STUN_BOMB"     x="4" y="0" />
    <item name="ITEM_STUN_BOMB"     x="5" y="0" />
    <item name="ITEM_STUN_BOMB"     x="6" y="0" />
  </loadout>
  <loadout name="LightPlasma">
    <item name="ITEM_PLASMA_PISTOL"      x="0" y="0" />
    <item name="ITEM_PLASMA_PISTOL_CLIP" x="2" y="3" />
    <item name="ITEM_ALIEN_GRENADE"      x="1" y="2" />
    <item name="ITEM_ALIEN_GRENADE"      x="2" y="2" />
  </loadout>
  <loadout name="MediumPlasma">
    <item name="ITEM_PLASMA_RIFLE"      x="0" y="0" />
    <item name="ITEM_PLASMA_RIFLE_CLIP" x="2" y="3" />
    <item name="ITEM_ALIEN_GRENADE"     x="1" y="2" />
    <item name="ITEM_ALIEN_GRENADE"     x="2" y="2" />
  </loadout>
  <loadout name="HeavyPlasma">
    <item name="ITEM_HEAVY_PLASMA_RIFLE"      x="0" y="0" />
    <item name="ITEM_HEAVY_PLASMA_RIFLE_CLIP" x="2" y="3" />
    <item name="ITEM_ALIEN_GRENADE"           x="1" y="2" />
    <item name="ITEM_ALIEN_GRENADE"           x="2" y="2" />
  </loadout>
  <loadout name="Grav">
    <item name="ITEM_GRAVITY_DISTORTION_LAUNCHER" x="0" y="0" />
    <item name="ITEM_GRAVITY_DISTORTION_DRONE"    x="4" y="0" />
    <item name="ITEM_GRAVITY_DISTORTION_DRONE"    x="5" y="0" />
    <item name="ITEM_GRAVITY_DISTORTION_DRONE"    x="6" y="0" />
    <item name="ITEM_PLASMA_PISTOL"               x="0" y="1" />
    <item name="ITEM_PLASMA_PISTOL_CLIP"          x="2" y="3" />
  </loadout>
  <!-- What an X-Corp soldier comes equiped with -->
  <loadout name="XCorpDefault">
    <item name="ITEM_ASSAULT_RIFLE"           x="0" y="0" />
    <item name="ITEM_ASSAULT_RIFLE_CLIP"      x="4" y="0" />
    <item name="ITEM_ASSAULT_RIFLE_CLIP"      x="4" y="1" />
    <item name="ITEM_GRENADE"                 x="1" y="2" />
    <item name="ITEM_GRENADE"                 x="2" y="2" />
    <item name="ITEM_SMOKE_GRENADE"           x="2" y="3" />
    <item name="ITEM_SMOKE_GRENADE"           x="3" y="3" />
    <item name="ITEM_PROXIMITY_GRENADE"       x="0" y="1" />
    <item name="ITEM_SATCHEL_CHARGE"          x="2" y="0" />
    <item name="ITEM_SATCHEL_CHARGE"          x="0" y="3" />
    <item name="ITEM_STUN_BATON"              x="6" y="0" />
  </loadout>

  <loadout name="Ventriculant">
    <item name="ITEM_VENTRICULANT_WEAPON" x="0" y="0" />
  </loadout>
  <loadout name="Silabrate">
    <item name="ITEM_SILABRATE_WEAPON" x="0" y="0" />
  </loadout>
  <loadout name="Spawn">
    <item name="ITEM_SPAWN_WEAPON" x="0" y="0" />
  </loadout>
  <loadout name="Artopod">
    <item name="ITEM_ARTOPOD_WEAPON" x="0" y="0" />
  </loadout>
  <loadout name="Terrordisc">
    <item name="ITEM_TERRORDISC_WEAPON" x="0" y="0" />
  </loadout>
  <loadout name="Raptor">
    <item name="ITEM_RAPTOR_WEAPON" x="0" y="0" />
  </loadout>
  <loadout name="Zombie">
    <item name="ITEM_ZOMBIE_WEAPON" x="0" y="0" />
  </loadout>

  <armor id="None" front="0" side="0" rear="0" under = "0">
      <susceptibility damageType="Piercing"  physical="1.0" stun="0.25"/>
      <susceptibility damageType="Fire"      physical="1.0" stun="0.25"/>
      <susceptibility damageType="Explosive" physical="1.0" stun="0.25"/>
      <susceptibility damageType="Laser"     physical="1.0" stun="0.25"/>
      <susceptibility damageType="Plasma"    physical="1.0" stun="0.25"/>
      <susceptibility damageType="Stun"      physical="0.0" stun="1.00"/>
      <susceptibility damageType="Melee"     physical="1.2" stun="0.25"/>
      <susceptibility damageType="Acid"      physical="1.6" stun="0.25"/>
      <susceptibility damageType="Smoke"     physical="1.0" stun="0.25"/>
  </armor>
  <armor id="ITEM_COMBAT_ARMOR" front="50" side="40" rear="30" under = "30">
      <susceptibility damageType="Piercing"  physical="1.0" stun="0.25"/>
      <susceptibility damageType="Fire"      physical="1.0" stun="0.25"/>
      <susceptibility damageType="Explosive" physical="1.0" stun="0.25"/>
      <susceptibility damageType="Laser"     physical="1.0" stun="0.25"/>
      <susceptibility damageType="Plasma"    physical="1.0" stun="0.25"/>
      <susceptibility damageType="Stun"      physical="0.0" stun="1.00"/>
      <susceptibility damageType="Melee"     physical="1.0" stun="0.25"/>
      <susceptibility damageType="Acid"      physical="1.0" stun="0.25"/>
      <susceptibility damageType="Smoke"     physical="1.0" stun="0.25"/>
  </armor>
  <armor id="ITEM_COMBAT_POWERSUIT" front="100" side="80" rear="70" under = "60">
      <susceptibility damageType="Piercing"  physical="1.0" stun="0.25"/>
      <susceptibility damageType="Fire"      physical="1.0" stun="0.25"/>
      <susceptibility damageType="Explosive" physical="1.0" stun="0.25"/>
      <susceptibility damageType="Laser"     physical="1.0" stun="0.25"/>
      <susceptibility damageType="Plasma"    physical="1.0" stun="0.25"/>
      <susceptibility damageType="Stun"      physical="0.0" stun="1.00"/>
      <susceptibility damageType="Melee"     physical="1.0" stun="0.25"/>
      <susceptibility damageType="Acid"      physical="1.0" stun="0.25"/>
      <susceptibility damageType="Smoke"     physical="1.0" stun="0.25"/>
  </armor>
  <armor id="ITEM_ANTI_GRAV_POWERSUIT" front="110" side="90" rear="80" under = "70" flyer="true">
      <susceptibility damageType="Piercing"  physical="1.0" stun="0.25"/>
      <susceptibility damageType="Fire"      physical="1.0" stun="0.25"/>
      <susceptibility damageType="Explosive" physical="1.0" stun="0.25"/>
      <susceptibility damageType="Laser"     physical="1.0" stun="0.25"/>
      <susceptibility damageType="Plasma"    physical="1.0" stun="0.25"/>
      <susceptibility damageType="Stun"      physical="0.0" stun="1.00"/>
      <susceptibility damageType="Melee"     physical="1.0" stun="0.25"/>
      <susceptibility damageType="Acid"      physical="1.0" stun="0.25"/>
      <susceptibility damageType="Smoke"     physical="1.0" stun="0.25"/>
  </armor>
  <armor id="Satyrian" front="8" side="6" rear="4" under="12">
      <susceptibility damageType="Piercing"  physical="1.0" stun="0.125"/>
      <susceptibility damageType="Fire"      physical="1.0" stun="0.125"/>
      <susceptibility damageType="Explosive" physical="1.0" stun="0.125"/>
      <susceptibility damageType="Laser"     physical="1.0" stun="0.125"/>
      <susceptibility damageType="Plasma"    physical="1.0" stun="0.125"/>
      <susceptibility damageType="Stun"      physical="0.0" stun="1.00"/>
      <susceptibility damageType="Melee"     physical="1.2" stun="0.125"/>
      <susceptibility damageType="Acid"      physical="1.6" stun="0.125"/>
      <susceptibility damageType="Smoke"     physical="0.0" stun="0.125"/>
  </armor>
  <armor id="SatyrianLeader" front="16" side="12" rear="8" under="12">
      <susceptibility damageType="Piercing"  physical="1.0" stun="0.125"/>
      <susceptibility damageType="Fire"      physical="1.0" stun="0.125"/>
      <susceptibility damageType="Explosive" physical="1.0" stun="0.125"/>
      <susceptibility damageType="Laser"     physical="1.0" stun="0.125"/>
      <susceptibility damageType="Plasma"    physical="1.0" stun="0.125"/>
      <susceptibility damageType="Stun"      physical="0.0" stun="1.00"/>
      <susceptibility damageType="Melee"     physical="1.2" stun="0.125"/>
      <susceptibility damageType="Acid"      physical="1.6" stun="0.125"/>
      <susceptibility damageType="Smoke"     physical="0.0" stun="0.125"/>
  </armor>
  <armor id="SatyrianCommander" front="24" side="18" rear="12" under="16">
      <susceptibility damageType="Piercing"  physical="1.0" stun="0.125"/>
      <susceptibility damageType="Fire"      physical="1.0" stun="0.125"/>
      <susceptibility damageType="Explosive" physical="1.0" stun="0.125"/>
      <susceptibility damageType="Laser"     physical="1.0" stun="0.125"/>
      <susceptibility damageType="Plasma"    physical="1.0" stun="0.125"/>
      <susceptibility damageType="Stun"      physical="0.0" stun="1.00"/>
      <susceptibility damageType="Melee"     physical="1.2" stun="0.125"/>
      <susceptibility damageType="Acid"      physical="1.6" stun="0.125"/>
      <susceptibility damageType="Smoke"     physical="0.0" stun="0.125"/>
  </armor>

  <armor id="Grey" front="4" side="3" rear="2" under="2">
      <susceptibility damageType="Piercing"  physical="1.0" stun="0.125"/>
      <susceptibility damageType="Fire"      physical="1.0" stun="0.125"/>
      <susceptibility damageType="Explosive" physical="1.0" stun="0.125"/>
      <susceptibility damageType="Laser"     physical="1.0" stun="0.125"/>
      <susceptibility damageType="Plasma"    physical="1.0" stun="0.125"/>
      <susceptibility damageType="Stun"      physical="0.0" stun="1.00"/>
      <susceptibility damageType="Melee"     physical="1.2" stun="0.125"/>
      <susceptibility damageType="Acid"      physical="1.6" stun="0.125"/>
